### ISSUE TITLE
change default style in component

### ISSUE THREAD

**Issue by izcream** [chakra-ui/chakra-ui-vue#227]
How can I change default style for some component 

Ex: I need to set default size of `c-input` to  lg (now i need to bind attr size in all input)

In Chakra-ui React I do it with `Input.defaultProps.size` its work normaly
so Can I do something like defaultPropsSize on chakra-ui-vue

Thanks

Ps. sorry for my bad english

**Comment by codebender828** [comment]
Hey @izcream ! 

There's two ways you can do that. Whenever you import the CInput component, since it's just an object, before you register locally it in the template you can set the default value to `lg` like this:

```vue
<template>
  <c-input />
</template>

<script>

import { CInput } from '@chakra-ui/vue';

// Sets the default prop value for size to 'lg'
CInput.props.size.default = 'lg';

export default {
  components: {
    CInput
  }
};

</script>
```

The second option would be to set the default prop value it like in the code above and register it globally so that you don't have to do this every time you import it.

```js
import Vue from 'vue';
import { CInput } from '@chakra-ui/vue';

// Sets the default prop value for size to 'lg'
CInput.props.size.default = 'lg';

// Register componenr globally
Vue.component('CInput', CInput)
```

Let me know if this works for you.

**Comment by izcream** [comment]
Thanks for guide 😍

**Comment by ruslankonev** [comment]
Hi! How to make this with chakra-loader?
