### ISSUE TITLE
is possible to add custom icon with slot?

### ISSUE THREAD

**Issue by izcream** [chakra-ui/chakra-ui-vue#228]
I have problem with custom icon In document tell only how to add in config
Is possible to do something like this ?

<img width="546" alt="Screen Shot 2020-05-31 at 21 39 44" src="https://user-images.githubusercontent.com/10282500/83355120-837ad880-a387-11ea-8110-928bd130e96b.png">

in chakra-react its easy to add custom with
<img width="847" alt="Screen Shot 2020-05-31 at 21 42 46" src="https://user-images.githubusercontent.com/10282500/83355138-b02ef000-a387-11ea-9c57-f28d18fa8133.png">

hope this can do in chakra-ui vue soon 😀

ps.thanks developer for port this from react to vue, with love 😍

ps2. document site sidebar cannot scroll on mobile. it's bug?

**Comment by codebender828** [comment]
Hey @izcream . I haven't actually tried this before. But I think it's work trying. I'll open a draft PR with a demo for you to play with to see how to works for you.

Re: Sidebar not being able to scroll:
 Yes.. I understand this issue is on mobile iOS devices? I haven't been able to reproduce it so I cannot debug it. If you're willing to look into it, I'd be grateful.

**Comment by izcream** [comment]
Thanks for answer. Yes problem about slider its happen on IOS(not test on android device yet😅) 

So i will closed this issue first and follow you instruction
