### ISSUE TITLE
[BUG]: Performance issue with hundreds of CBox nodes. 

### ISSUE THREAD

**Issue by wuyongzhi** [chakra-ui/chakra-ui-vue#241]
**Describe the bug**
The input control's response to input is slow when there are too many components on the page.

**To Reproduce**
1. create 100 `CBox` on a page, and a `CInput`
2. bind the `CInput` v-model  property to a var
3. input some text on `CInput`
4. You will see the respond is slowly

I create a repostory to show this issue, https://github.com/wuyongzhi/chakra-performance-issue-sample

**Comment by wuyongzhi** [comment]
Thanks for your help @codebender828. 

I try to add a raw html input to the page , still occurrenced.

So I'm not sure how it's caused and have tried to look at the code, but don't yet know how to go about fixing it, I'll stay tuned and thanks again for your help!

**Comment by codebender828** [comment]
Hey @wuyongzhi !

Just to share a brief update. @koca and I have been doing some investigation here, and a large portion of the performance expense has to do with how the Chakra primitives are managing their `props`.

Because of the props architecture with Vue, quite a lot of logic runs in between merging of consumer + default props, and passing the styles object to styled system. We have some ideas so you're welcome to join our discussion on this topic.

For quicker responses, we have a discord channel here where we'll talk about this. So contributors interested in talking about this issue so you're welcome to join us here 👇🏽:

https://discord.gg/FAUwFT

Cheers 💚

**Comment by izcream** [comment]
Same i found when bind v-model to component(ex slider/input) its will laggy😂
didnt try manual binding value and event yet😄
