### ISSUE TITLE
[Bug]: `CInput` @input event not emitted when wrapped inside `CInputGroup` component

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#292]
**Describe the bug**
When the `CInput` component is wrapped inside the `CInputGroup` the @input event is not emitted.

**To Reproduce**
1. Go to https://codesandbox.io/s/gifted-torvalds-c9nud?file=/src/App.vue
2. Type in first input. Logs are not shown in console.

**Expected behavior**
`@input` events should be emitted for inputs wrapped inside the `CInputGroup` component

**Comment by fugaku** [comment]
Any workaround while waiting for the bug resolved ?

**Comment by codebender828** [comment]
Hey @fugaku. At the moment I'm not really sure.

If it's urgent for your case, you could try using the native `@input` or `@input.native` events to get the input event and values.

Will take a look at this tomorrow since I have an idea on how this can be fixed.

**Comment by codebender828** [comment]
Hey @fugaku I'm currently working on this, and I'd like to see your current use case for listening to events so I can decide how to go forward with the fix for this. Is there something in particular you wanted to do?

**Comment by fugaku** [comment]
Hey @codebender828 

Should I try to create a repo with my use case for you ?

**Comment by codebender828** [comment]
Yes. That would be helpful. 👍🏽

**Comment by dombavetta** [comment]
Hey guys, I ran into this as well during my development but forgot to record it to later create an issue. This problem is not only isolated to the `input` event, you will also experience this with others such as `focus` and `blur`. The `.native` workaround proposed by @codebender828 will work in the meantime, however, I would like to pose an additional workaround that I found myself using. Oddly enough you can successfully listen to the input event my attaching listener through the component instance's `$on` method. 

```vue
mounted() {
    this.$refs.inputGroupInput.$on("input", this.handleInputFromVM);
}
```

I've forked @codebender828 codesandbox demonstrating this incase you were curious. Check out the sandbox [here](https://codesandbox.io/s/purple-wildflower-tkprn?file=/src/App.vue).

**Comment by codebender828** [comment]
Thanks for sharing, @dombavetta ! There's a couple of caveats with how functional components handle events for cloned children. So seeing how people are using these events is helpful. I was considering rewriting the `CInputGroup` to a stateful component, but was holding off for a bit.

**Comment by fpoliquin** [comment]
I've hit the same issue. I was trying to wrap the c-input-group to build a higher level search box component which needs to expose the "input" event.

**Comment by ajacquierbret** [comment]
Same here, I had to use a watcher on the v-model value in order to get an input event.

**Comment by lianulloa** [comment]
Hi guys, is there any update about this? Still have the same issue. In my case I was trying to use `keydown.enter`, `keypress.enter` or `keyup.enter`. Neither worked @dombavetta @codebender828

**Comment by peoray** [comment]
Closing this as it looks to be fixed (update in the next release). Feel free to reopen if this isn't the case
