### ISSUE TITLE
[ChakraLoaderPlugin Error] No matching rule for vue-loader found

### ISSUE THREAD

**Issue by harrytran998** [chakra-ui/chakra-ui-vue#335]
**Describe the bug**
When I upgrade @charkra/ui-nuxt version from `0.0.13` to `0.1.0` --> This had an error.

```
[ChakraLoaderPlugin Error] No matching rule for vue-loader found.                                                                                                                                         
Please make sure that vue-loader is installed and included in your webpack config.
```

**Expected behavior**
I upgrade this package because I want my team work with the new properties CSS like `place-content="center space-between"`. So hope you or your team will fix it!

**Screenshots**
![image](https://user-images.githubusercontent.com/24296018/94895682-18b4e780-04b6-11eb-9b98-e06ce0ac9f43.png)

**Desktop (please complete the following information):**
 - OS: MacsOs 10.15.4

**Comment by dombavetta** [comment]
Hey @harrytran998, can you provide a link to a reproducible product? I attempted to recreate the issue in [this CodeSandbox](https://codesandbox.io/s/chakra-ui-vueissue335-i1tqm) but was unsuccessful. Feel free to fork the sandbox in an attempt to reproduce. The sandbox currently uses @chakra-ui/nuxt v0.0.13, I attempted to upgrade to v0.1.0 and was not blocked by the issue you described above.

**Comment by bmulholland** [comment]
@dombavetta The sandbox you linked is broken, so I can't use it to reproduce. Steps to break the sandbox: 1. Fork it, 2. Make any change (whitespace) to package.json 3. CodeSandbox refreshes packages and the project breaks.

Here's a video: https://recordit.co/UYAV3fjSgT

**Comment by bmulholland** [comment]
Well, I got it working, not sure how considering that breakage.

@dombavetta here's a working repro. Aside from upgrading to 0.1.0, the other key piece is to add the chakra-loader package and configure it in nuxt.config.js. (I also had to restart the CodeSandbox server for it to show up). Those are the only changes I made.

https://codesandbox.io/s/chakra-ui-vueissue335-forked-vc4uo?file=/package.json

**Comment by bmulholland** [comment]
Well, I figured out a way to fix it: use [the new auto-import configuration provided with 0.1.0](https://vue.chakra-ui.com/auto-import-components#with-nuxt.js). This was mentioned in the [Changelog](https://github.com/chakra-ui/chakra-ui-vue/blob/develop/packages/chakra-ui-nuxt/CHANGELOG.md#010). However, neither the changelog nor the docs indicate that this is a **breaking change**, and that projects _must_ migrate to the new format. If using Semver, the version increment doesn't indicate that either.

I'd suggest either updating the docs and version to indicate a breaking change, or issue a change to support the old configuration method as well.

**Comment by codebender828** [comment]
Hey @harrytran998  @bmulholland ! Thanks for helping us catch this issue.  

Thanks @dombavetta For running point on this so far.

I suspect this issue might have to do with the indexing of the webpack plugin registration from inside the module. I can investigate this today to see why it differs from when it's manually configured in the `nuxt.config.js` file. It may need a bit of baby-sitting to do.

**Comment by codebender828** [comment]
@harrytran998 For your project, As a workaround, your team can still use the `place-content` properties by upgrading the `@chakra-ui/vue` package independently to `v0.6.6`

**Comment by codebender828** [comment]
> Well, I got it working, not sure how considering that breakage.
> 
> @dombavetta here's a working repro. Aside from upgrading to 0.1.0, the other key piece is to add the chakra-loader package and configure it in nuxt.config.js. (I also had to restart the CodeSandbox server for it to show up). Those are the only changes I made.
> 
> https://codesandbox.io/s/chakra-ui-vueissue335-forked-vc4uo?file=/package.json

**Solution**
1. For **`@chakra-ui/nuxt@^0.1.0`**, In your `nuxt.config.js` file, you no longer need to install the `ChakraLoaderWebpackPlugin` in `build.extend` option. This handled internally.
2. This also means that you no longer need to install the `chakra-loader` package yourself, since it's an internal dependency for the `@chakra-ui/nuxt@^0.1.0`.

**The cause of the issue**
After digging into this, I think I realize the cause of this problem. After upgrading `@chakra-ui/nuxt` to `v0.1.0`, you needn't  manually setup the `chakra-loader` plugin in `nuxt.config.js` file. I'm not sure why the error comes up if you manually set `chakra.config.autoImport: true` and add then proceed to add the plugin in the `build.extend()` option of the `nuxt.config.js` file.

**Going forward**
At the time of developing this feature, I didn't encounter this problem. After seeing the cause of the issue, I can see why this would have been better to instead make a major change in the package versioning. I may do this in the next release to account for this issue. I'm also interesting in hearing feedback around this problem. 

So for now I'll tag it as having a work-around, but will leave the issue open to facilitate this.

**Comment by bmulholland** [comment]
@codebender828 I was reflecting on this and realized that actually the package is a 0.x version, which probably means that some breakage is to be expected. The higher expectations and semver probably come after 1.0.0. My bad on bringing those expectations too soon! So IMHO it's probably fine to do this. Perhaps a one-line update to the changelog to state that action is required on upgrade would be enough to deal with it for now? That's my personal go-to when something breaks after upgrade.
