### ISSUE TITLE
GridItem component

### ISSUE THREAD

**Issue by IHIutch** [chakra-ui/chakra-ui-vue#351]
**Is your feature request related to a problem? Please describe.**
I noticed the React library has a GridItem component, this seems helpful for configuring column spans and such. I am much more of a bootstrap person, so I'm used to classes like `col-md-8`, `offset-md-8`...

**Describe the solution you'd like**
A component that accepts props like `colSpan`, `colStart`, `colEnd`... 
See: [https://chakra-ui.com/docs/layout/grid#griditem-props](https://chakra-ui.com/docs/layout/grid#griditem-props)

**Describe alternatives you've considered**
I've created my own component that handles inline styles for the above-mentioned props.

**Additional context**
If there is a way to do this already, please let me know. I tried searching issues for "Grid Item", but there is nothing. If a solution exists, maybe it can just be added to the docs?

**Comment by codebender828** [comment]
Hey @IHIutch Thanks for the feature request!

Currently v0 doesn't implement this as a component. I don't see any harm in adding a component like this to the project. However, I'm not yet sure if it should be implemented in the `v0` library core, as a recipe, or in user land as a custom component. Your points are pretty good ones. 🤔 I haven't yet encountered this use case yet.

Since I'm not really sure which exact direction to take, I'm happy to covert this issue into a discussion if you have some more ideas or if other users may feel the same way so as to add this to the core `v0` library.
