### ISSUE TITLE
Add DateInput to the Vue Chakra Components

### ISSUE THREAD

**Issue by abelbordonado** [chakra-ui/chakra-ui-vue#472]
First of all, appreciate the great library of vue-chakra and the work behind. Is being really handfull for our projects.

**Is your feature request related to a problem? Please describe.**
I miss an important input functionality which is the `Date` Input, either `Time`  , `Month`,  `DateAndTime` combinations.
We can use the HTML5 prosal but is not as good looking (have a break of design with rest of the framework) and is hard to control by code (close and open the pop up) and may not compatible with other browsers.

**Describe the solution you'd like**
Make a DatePicker is not a simple task. But I give a link to a great solution done by `ant.design` which had been use without problem in many projects before moving to vue.

https://ant.design/components/date-picker/
![image](https://user-images.githubusercontent.com/37141039/128314879-f6ee4b87-e0e8-4e51-9fdd-9b6ec33b48e1.png)
![image](https://user-images.githubusercontent.com/37141039/128314924-c7311e12-0e4a-4f97-b1a6-db37970f149f.png)
![image](https://user-images.githubusercontent.com/37141039/128314972-73caaa74-0ff0-4a5d-b842-7d9e36889f38.png)

**Describe alternatives you've considered**
Workaround is use another different plugin for the date
https://www.npmjs.com/package/vue2-datepicker

Kindly regards for your consideration

**Comment by codebender828** [comment]
Hi, @abelbordonado ! Thank you for the kind words! We appreciate it and are encouraged.

We also appreciate the suggestion to include a higher-level component like a date-picker to Chakra UI. After some consideration our team has agreed that the best way for us to continue with the future of Chakra UI would be to focus primarily on primitive/or slightly higher than primitive components.

Building a date picker with Chakra UI would require us to make compromises on the principles of the component API design that Chakra UI adheres to. For example, One of Chakra's design principles is to provide compound components so that each part of complex components would be styled easily by the user. With a date picker, giving this flexibility to the user would make it very complex to implement, and consequently style.

For this reason, we see it reasonable to not implement a date picker into the core library, but rather can be done in user land, as and when needed.

Here's an example of the date picker implemented in React user land.
https://github.com/chrisbull/react-chakra-date-picker

If you'd like to implement this for Vue.js, we're happy to feature it in the community ✌️

Will close this for now.
